// Generated by scripts/write-production-env.js — do not edit apiUrl/razorpayKeyId manually before deploy.
export const environment = {
  production: true,
  apiUrl: '__API_URL__',
  firebase: {
    apiKey: 'AIzaSyDziBrk5HCpi4CarfqshoOJ8ZmpTBPuTr8',
    authDomain: 'instafruit99-13755.firebaseapp.com',
    projectId: 'instafruit99-13755',
    storageBucket: 'instafruit99-13755.firebasestorage.app',
    messagingSenderId: '706736900017',
    appId: '1:706736900017:web:a3d09d102d650a922a5f90',
    measurementId: 'G-PY5G388NYE',
  },
  razorpayKeyId: '__RAZORPAY_KEY_ID__',
  razorpayTestAmountInr: null as number | null,
  cloudinary: {
    cloudName: 'dnmuwin6h',
    uploadPreset: 'instafruit_products',
  },
};
